/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if `lstat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef HAVE_LSTAT_EMPTY_STRING_BUG */

/* Define to 1 if your system has a working `malloc' function. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if `stat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef HAVE_STAT_EMPTY_STRING_BUG */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strcasecmp' function. */
#define HAVE_STRCASECMP 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the `strftime' function. */
#define HAVE_STRFTIME 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strrchr' function. */
#define HAVE_STRRCHR 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if `lstat' dereferences a symlink specified with a trailing
   slash. */
#define LSTAT_FOLLOWS_SLASHED_SYMLINK 1

/* Defines the username of the Apache user */
#define OPT_APACHE_USER "wwwrun"

/* Define if you want to disable the check, wether script resides in
   DOCUMENT_ROOT */
/* #undef OPT_DISABLE_CHECKPATH */

/* Defines path to logfile */
#define OPT_LOGFILE "/var/log/httpd/suphp_log"

/* Defines the min GID allowed to run scripts */
#define OPT_MIN_GID 100

/* Defines the min UID allowed to run scripts */
#define OPT_MIN_UID 100

/* Define if you want to proceed even if GID of the script is not listed in
   /etc/group */
/* #undef OPT_NO_GROUP */

/* Define if you want to proceed even if UID of the script is not listed in
   /etc/passwd */
/* #undef OPT_NO_PASSWD */

/* Defines path to PHP interpreter */
#define OPT_PATH_TO_PHP "/usr/bin/php"

/* Define if you want to set UID/GID to the user/group specified in the Apache
   configuration */
/* #undef OPT_USERGROUP_FORCE */

/* Define if you want to set UID/GID to the owner of the script */
#define OPT_USERGROUP_OWNER 1

/* Define if you want to set UID/GID to the user/group specified in the Apache
   configuration AND check if these settings match the UID/GID of the script
   */
/* #undef OPT_USERGROUP_PARANOID */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "sebastian.marsching@suphp.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "suphp"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "suphp 0.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "suphp"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.5"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef gid_t */

/* Define to `int' if <sys/types.h> doesn't define. */
/* #undef uid_t */
